package vn.ptit.procon.runtime;

public enum SemanticParityStatus {
    VALIDATED,
    LIVE_OBSERVED,
    LIVE_MATCHED_FOR_TESTED_SCENARIO,
    PARTIALLY_OBSERVED,
    PARTIALLY_LIVE_VERIFIED,
    CORRECTED_LOCALLY,
    CORRECTED_AND_LIVE_SUPPORTED,
    NOT_FULLY_VERIFIED,
    NOT_TESTED,
    MISMATCH
}
