package vn.ptit.procon.planner;

/** Search guidance variants sharing the same bounded anytime engine. */
public enum AnytimeSearchPolicy {
    ORIGINAL,
    HARVEST,
    CONTENTION,
    ANYTIME_ARRIVAL_CONTENTION,
    ANYTIME_WEIGHTED_ARRIVAL_CONTENTION,
    ANYTIME_RISK_ADJUSTED,
    ANYTIME_INTENT_AWARE,
    ANYTIME_DIVERSE_INTENT_AWARE,
    ANYTIME_STRATIFIED_INTENT_AWARE,
    ANYTIME_STRATIFIED_COMMITMENT_AWARE,
    ANYTIME_STRATIFIED_SEMI_COMMITMENT_AWARE,
    ANYTIME_STRATIFIED_SEMI_COMMITMENT_HORIZON_AWARE,
    ANYTIME_STRATIFIED_SEMI_COMMITMENT_HARVEST_HORIZON_AWARE,
    ANYTIME_STRATIFIED_RELATIVE_MARGIN_AWARE,
    ANYTIME_STRATIFIED_REPLACEMENT_AWARE_RELATIVE_MARGIN,
    ANYTIME_STRATIFIED_COUPLED_COMPETITIVE_MARGIN,
    ANYTIME_STRATIFIED_HYBRID_CALIBRATED_MARGIN,
    ANYTIME_STRATIFIED_HYBRID_DIVERSE_CANDIDATES,
    ANYTIME_STRATIFIED_TEAM_ALLOCATED_HYBRID,
    ANYTIME_STRATIFIED_CAPACITY_COMPETITIVE
}
